src/main/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataCyclingDistanceSpeed.java

solve the issue mention in the ticket: 
https://github.com/rilling/OpenTracks-Concordia/issues/65

[Technical Debt] #65 correct name for variable timeDiff_ms

---

src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java

1. Removed deprecated code and implemented latest class.
1. #61 
By opening this pull request, I am providing my contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).
No new dependencies.

[Technical Debt] #61 Removed depricated code and updated to newest class

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/FilterDialogFragment.java

Removed Instance variable and declared it as local variable
https://github.com/rilling/OpenTracks-Concordia/issues/68
No dependences added

[Resolved: #68] - Removed Instance variable and declared it as local variable

---

src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java

Updated the constant naming convention in TrackFileFormat.java
[Issue 33](https://github.com/rilling/OpenTracks-Concordia/issues/33)

Fixed constant naming convention - Issue 33

---

src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/UnitSystem.java

Fixed - Issue 71
https://github.com/rilling/OpenTracks-Concordia/issues/71

Fixed - Issue 71

---

src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java

Rename Field altitudeGain_m to altitudeGain

Rename Field altitudeGain_m to altitudeGain

---

src/main/java/de/dennisguse/opentracks/util/TrackUtils.java

Fix issue located in [util/TrackUtils.java]
https://github.com/rilling/OpenTracks-Concordia/issues/58

#58 Fix issue in [util/TrackUtils.java]

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

Usage of generic exception fixed by adding a more specific exception
[https://github.com/rilling/OpenTracks-Concordia/issues/145]
Please refrain from introducing new libraries without consulting the team.

ChartView.java | Usage of generic exception - FIX

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/FilterDialogFragment.java

Removed filterDialogListener Instance variable to local variable in the relevant methods
Change filterDialogListener Instance variable to local variable #154
[
](https://github.com/rilling/OpenTracks-Concordia/issues/154)
No dependencies added

[Resolved - #154]: Removed filterDialogListener Instance variable to local variable in the relevant methods

---

src/main/java/de/dennisguse/opentracks/viewmodels/ClockViewHolder.java

https://github.com/rilling/OpenTracks-Concordia/issues/162
By opening this pull request, you …

Made changes for the setTextAppearance.

---

src/main/java/de/dennisguse/opentracks/viewmodels/ClockViewHolder.java

Updated ClockViewHolder.java
#225  …

Solved issue#225

---

src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java

Remove deprecated method call as described by #182 
#182 
Please refrain from introducing new libraries without consulting the team.

Remove use of deprecated defaultUnitSystem

---

src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalsFragment.java
src/main/res/layout/interval_list_view.xml

Code changes for the https://github.com/rilling/OpenTracks-Concordia/issues/231
Adding new field in the interval layout, and setting the value appropriately

Intervals tab pace

---

src/main/res/menu/track_list.xml
src/main/res/values/strings.xml

Add an entry to the Profile page in the buttom dropdown menu
https://github.com/rilling/OpenTracks-Concordia/issues/247
Please refrain from introducing new libraries without consulting the team.

added the profile option button in dropdown menu

---

.idea/codeStyles/Project.xml
build.gradle
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/xml/settings_import_export.xml

Issue 243 exporting importing trackdata to from onedrive

---

src/debug/java/de/dennisguse/opentracks/ViewTrackMap.java
src/debug/res/layout/statistics_recorded_enhancement.xml
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/res/layout/statistics_recorded.xml

Added a method to TrackRecordedActivity.java which opens the activity ViewTrackMap.java to view the map

Added activity to view the map

---

src/main/java/de/dennisguse/opentracks/data/models/Calories.java
src/main/java/de/dennisguse/opentracks/data/models/CaloriesFormatter.java

Created Model Classes Calories and Calories Formatter.
This Pull Request is related to the issue
[Link to the Issue](https://github.com/rilling/OpenTracks-Concordia/issues/6)
A clear and concise description of …

Created Model classes Calories and Calories Formatter

---

src/main/java/de/dennisguse/opentracks/ui/util/WeatherUtils.java

Added utility class for displaying weather info

---

src/main/java/de/dennisguse/opentracks/chart/ChartPoint.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java

Altered classes - ChartView and ChartPoint by group 8, and TrackStatistics by group 7.

Issue#245 added average moving pace in charts

---

src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/layout/statistics_recorded.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_user_interface.xml

Reverts rilling/OpenTracks-Concordia#326

Revert "Group #14"

---

src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/settings/SettingsCustomLayoutEditActivity.java
src/main/java/de/dennisguse/opentracks/settings/SettingsCustomLayoutListActivity.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java

Resolved issues related to technical debts by each team member (SonarQube Analysis).
- https://github.com/rilling/OpenTracks-Concordia/issues/376 - Pankaj
- …

Create user profile - Resolved Technical Debt (SonarQube Analysis)

---

src/main/res/layout/user_profile_setting.xml

We have successfully added remaining text fields, such as Height, weight, and Date of Birth on User's Profile settings page.
#407 
#408 
#409 
#315 
#305 
#247 
#5

Group #19. Adding relevant text fields in User's profile settings page.

---

src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java

Fixed issue 417

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
src/main/res/layout/statistics_recorded.xml

Removing Code Smells and adding UI changes as an enhancement.
**Link to the issue**
https://github.com/rilling/OpenTracks-Concordia/issues/396
https://github.com/rilling/OpenTracks-Concordia/issues/397
https://github.com/rilling/OpenTracks-Concordia/issues/398
https://github.com/rilling/OpenTracks-Concordia/issues/403
https://github.com/rilling/OpenTracks-Concordia/issues/404
https://github.com/rilling/OpenTracks-Concordia/issues/406

Features/group 3/soham

---

src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Code fix for the latest merge
Issue #243

Code fix for recent merge

---

src/debug/res/layout/statistics_recorded_enhancement.xml
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/ViewTrackMap.java
src/main/java/de/dennisguse/opentracks/data/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/data/models/LocationPoints.java
src/main/res/layout/track_recorded.xml

Storing and accessing lat and lon in viewTrackMap

---

src/main/java/de/dennisguse/opentracks/fragments/ChooseActivityTypeDialogFragment.java

Update ChooseActivityTypeDialogFragment.java and perform PMD issue changes

---

src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java

fixed part in fragment,deleting unused method

---

src/main/java/de/dennisguse/opentracks/util/ExportUtils.java

463 use try with resources or close this outoutstream in a finally clause

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java

#503. Finish technical debt of misleading column usage.

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

resolved sonarqube related issue-436

---

src/main/java/de/dennisguse/opentracks/ui/markers/MarkerDetailFragment.java

Remove multiple return from a method
[(If available): The link to the issue that this pull request solves.](https://github.com/rilling/OpenTracks-Concordia/issues/529)

Remove multiple returns issue#529

---

build.gradle
gradle.properties
src/debug/res/layout/statistics_recorded_enhancement.xml
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/ViewTrackMap.java
src/main/java/de/dennisguse/opentracks/data/models/LocationPoints.java
src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/ConfirmDeleteDialogFragment.java
src/main/java/de/dennisguse/opentracks/ui/util/DialogUtils.java

Remove usage of deprecated method: getParcelableArray() in ConfirmDeleteDialogFragment.java
#516 
Please refrain from introducing new libraries without consulting the team.

[ RESOLVED #516 ] - Remove usage of deprecated method: getParcelableArray() in ConfirmDeleteDialogFragment.java

---

src/main/java/de/dennisguse/opentracks/chart/ChartFragment.java

resolved issue#432

---

ActivityUtils.java

Solved technical debt #558
Declare "VIBRATE" and all following declarations on a separate line
#558

#558 technical debt
